### ISSUE TITLE
Issue between sip and pyqt5

### ISSUE THREAD

**Issue by Sulstice** [ABI-Software/abics#1]
There seems to be an issue between Sip and PyQt5, I can't seem to get past the installation when running `abics.sh`

Environment:
   - Mac OSx High Sierra v10.13 
   - Python v3.7.6
   - Conda v4.8.3

   
    python userinterface/ABICS.py                                                                                                                                                                   
    Traceback (most recent call last):
    File "userinterface/ABICS.py", line 38, in <module>
        import sip
    ModuleNotFoundError: No module named 'sip'

Seems to be a dependency clash.

**Comment by Jagirhussan** [comment]
Hi
   I do not have access to OSx Sierra, I tried it on OSx 10.15 Catalina, python 3.7.5 and it works. sip is installed along with pyqt5. In case there are conflicts due to the python version, I suggest that you create a virtual environment say with python=3.6 or python=3.7 and install the stack.

Thanks
Jagir

**Comment by willhunt** [comment]
I had this problem with Python 3.8. Changing to Python [3.6.8](https://www.python.org/downloads/release/python-368/) solved this for me (windows).
